# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa27dea418e8c6ac23bff366f33098099eb6e783d145b593c3dfe5e0c70be43d5a687f8d363627109a3d1245561e1820149485753f61c10e5bb6af69a7d0a18

test:
  secret_key_base: 5fa0891323239fef2ebbb316e5f2177f36f9e45bfd6658e2b3e4d8138bf291c8c0934abbf04ac267e16ef68e396194222cf860d9255e1949d0b2e33a8351df18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
